name: Run Python Script

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  run-python:
    runs-on: ubuntu-latest
    # container:
    #   image: python:3.11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run bash
        run: |
          ls -lah
          pwd
          echo "hello, nostrverse"
